
from playwright.sync_api import sync_playwright
import json, time, os

OUT_DIR = "/opt/data/memories/cookies"
os.makedirs(OUT_DIR, exist_ok=True)
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/154.0.0.0 Safari/537.36"

SITES = {
    "douyin":   [".douyin.com", "www.douyin.com", "iesdouyin.com", ".iesdouyin.com"],
    "bilibili": [".bilibili.com", "www.bilibili.com", ".b23.tv"],
    "zsxq":     [".zsxq.com", "www.zsxq.com"],
    "12306":    [".12306.cn", "kyfw.12306.cn"],
}

with sync_playwright() as p:
    b = p.chromium.connect_over_cdp("http://192.168.199.184:9222")
    ctxs = b.contexts
    print("contexts:", len(ctxs))
    ctx = ctxs[0]
    allc = ctx.cookies()
    npages = sum(len(c.pages) for c in ctxs)
    print("pages:", npages)
    print("cookie 总数:", len(allc))

    # 存成 playwright 格式（每站一个 json，可直接 connect 用）
    for name, doms in SITES.items():
        sel = [c for c in allc if any(d in c["domain"] for d in doms)]
        if not sel:
            print(f"  {name}: 0 cookie"); continue
        with open(f"{OUT_DIR}/{name}.json", "w", encoding="utf-8") as f:
            json.dump(sel, f, ensure_ascii=False, indent=1)
        # Netscape 格式给 yt-dlp
        lines = ["# Netscape HTTP Cookie File", "# Generated by 小卡 from CDP bridge", ""]
        for c in sel:
            dom = c["domain"]
            flag = "TRUE" if dom.startswith(".") else "FALSE"
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure") else "FALSE"
            exp = c.get("expires", 0) or 0
            name_ = c["name"]
            val = c["value"]
            lines.append(f"{dom}\t{flag}\t{path}\t{secure}\t{int(exp)}\t{name_}\t{val}")
        with open(f"{OUT_DIR}/{name}_cookies.txt", "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        print(f"  ✅ {name}: {len(sel)} cookie -> {name}.json + {name}_cookies.txt")
    b.close()
